### ISSUE TITLE
WIP Todo List

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/demsausage-v3#1]
# Foo
- **Bug Fixes**
  - ~What caused the [Failed to fetch](https://sentry.io/democracy-sausage/democracy-sausage/issues/481023098/) error? Maybe make the `setTimeout` hack more robust?~
  - ~What caused [Type error](https://sentry.io/democracy-sausage/democracy-sausage/issues/482352566/)?~
  - ~What caused [Network error when fetching](https://sentry.io/democracy-sausage/democracy-sausage/issues/482187559/)?~
- **Enhancements**
  - [x] Cache the MapBox Static Images in the DB to avoid unnecessary use of our API quota OR nix them and design a different chooser UI
  - [x] Cleanup has_other from Canning and earlier
  - [x] Why isn't Mitcham PS turning up in search properly (c.f. Twitter)
  - [x] Better loading screen

# After Tasmania
- [x] Load SA polling place data
  - [x] Reply to email from St Gabriel’s
- **Questions**
  - [x] What's required to make admin work better on mobile?
  - [x] Historically are there (m)any polling places that have foods that aren't sausage/cake, but no sausage and cake?
  - [x] Google logout issue
- **Migrate to new infrastructure**
  - [x] Can we keep the API on GS if we move the two static sites?
  - [x] ~How to handle things that require cron job-type functionality (emails for admins, database backups)~
  - [x] Move the two static sites to S3 behind CloudFront with automatic deploys from Travis.
    - [x] CloudFront vs CloudFlare. Does CloudFront do the fancy gzipping and content optimisation that CloudFlare does?
  - [x] Add HTTPS versions of the site to Google and Bing's webmaster tools.
- **Enhancements: Admin Console**
  - [x] A button to manually trigger GeoJSON generation for an election
  - [x] Daily emails for admins
  - [x] Add a link to the main site on the Admin Console's ResponsiveDrawer 
- **Enhancements: Public Site**
  - [x] Add geolocation for finding stalls (+ Google Analytics events)
  - ~What are the pre-conditions to get fullscreen via manifest.js?~
  - [x] Log Google Analytics events for using the ElectionChooser and loading an election (or part of Election Chooser?) and finding a polling place
  - [x] Make the election chooser change the URL to something human readable like `/south-australia-2018`. This would also make the back button work with tabs.
  - [x] Make stall descriptions a textarea
  - [x] We're not showing the `free text` field on finder or querying a polling place
  - [x] Clarify the Add Stall `stall description` field to talk less about food and more about the purpose. Add the `free text` field as an additional entry option for e.g. cold drinks
  - [x] Add GA events to map querying
  - [x] Think about election switching across Map, Find, and Sausagelytics wrt. active elections and historical
  - [x] Add an "No active elections" state to Add Stall. Maybe telegraph upcoming elections?
  - [x] AddStall as a Stepper?

# Sprint to the line
- [x] Make selecting polling places on the map work
- [x] Quick tidy up of the submitted/approved email notices
- [x] Quick SQL injection/unicode test
- [x] Make BottomNav active icons work
- [x] Move first_report/latest_report to the server and capture unofficial polling places
- [x] The "sometimes polling places don't load on the map until you pan/zoom" issue
- [x] Client-side error capture
- [x] Server-side error capture
- [x] Google Analytics
- [x] ~Does import deal with detecting dupes? Does it fail or warn/check?~ (It auto merges and flags errors.)
- [x] Add static pages
- [x] MVP of desktop responsive view
- [x] Fix the issue with `has_bbq` in `markPendingStallAsReadAndAddUnofficialPollingPlace()`
- [x] Display stall info on the stall cards too
- [x] Deploy and test on more browsers, devices, and an iPad
  - [x] AppBar doesn't fit the logo + title on an iPhone 5S (Chrome)
  - [x] EmptyState on Finder appears whilst there are GoogleAutocomplete results
  - [x] Clicking on items in the ResponsiveDrawer doesn't close the drawer
  - [x] Maybe disable autoFocus on AddStall
  - [x] Clarify that we won't spam you
- [x] Create Tassie election. Test end-to-end process.
- [x] Ship it! Announce!
- [x] ~Is CloudFlare working on the main domain?~
- [x] Update "Add Stall" form to search the actual polling places if `polling_places_loaded` is true.
- [x] Get and load polling place data for Tassie
  - [x] Website description issue on Google and Bing
  - [x] Problem editing http://admin.democracysausage.org/election/15/polling_places/61/edit
  - [x] Fix setting first_report/last_report for all polling places loaded
  - [x] Fix `pendingStallCount` notice on ElectionPollingPlaceLoaderContainer
  - [x] Make the unknown icons appear below everything else
  - [x] http://admin.democracysausage.org/stalls/12/ breaks if has_other is null
  - ~Data load issue: [Divisions]~(https://www.tec.tas.gov.au/House_of_Assembly_Elections/StateElection2018/PollingPlaceLists.html) didn't come with the KML file
- [x] Smarter pre-fill of info ("Merge"?) to make the approval process faster for high-volume elections. The goal being that users can approve stalls on their phone in < 1 minute.
- **Support multiple active elections at once**
  - [x] Support automatically turning off elections. Is the whole concept of `active` even valid then? c.f. Election opening dates
  - [x] Add an active election chooser to AddStall. Update all uses of currentElection to use `stalls.elections_id`. Likewise, map querying. GeoJSON loading how? Display an election card even if there's only one election? How does the public map allow choosing between elections?
  - **Admin UI**
    - [x] Refactor `elections.elections`
    - [x] Update reference to `elections.current_election_id`
    - [x] Add `short_name` as an editable field
    - [x] Add `react-responsive` for better Drawer and BottomNav (Election, Pending Stalls, Polling Places)
    - [x] Review responsiveness on mobile
    - [x] Update Pending Stalls to group by election
    - [x] Update Stall Approver to clearly show the election being edited
    - [x] Can we refactor to make the "two elections on one day" workflow nicer for admins?
  - [x] How to support having a "primary active election"?
  - [x] Add an 'active election' indicator to the public site?
  - [x] Setup Batman By-election, Reply to email, and Tweet promoting SA and Batman being live
- [x] Make BottomSheet sticky
- [x] Support 'Has Run Out' icons again

## Adding stalls before polling places are loaded
- [x] Add `polling_places_loaded` INT DEFAULT 0. Update interface and SQLite `CREATE TABLE` definitions.
- [x] Add a control to switch `polling_places_loaded` on the elections manager
- [x] When an election is created, create an empty table for it. Ensure an empty GeoJSON file is also created.
- [x] Check code that relies on db_table_name being empty to work - it will always be set now
- [x] Create "Add Stall" form with an address lookup if `polling_places_loaded` is false.
- [x] ~Briefly tells users why address lookup~
- [x] Try to pull the place name for polling_place_name from address lookup. Also state.
- [x] Update the pending stall approver to check for duplicates (by location) and prompt the user to edit the relevant polling place. Block traditional 'approving'. Allow to 'delete'.
- [x] Deal with two dupes in the queue and approving one?
- [x] If `polling_places_loaded` is false, APPROVING a stall will create a new 'fake' polling place in its table. Update GeoJSON. Also update its polling_place_id so it'll in turn be updated by the import process. And null out stall_location_info since it's now tied to a polling place that will be migrated by the import process.
- [x] Can we safely remove `division` from the required fields for a polling place? Ditto `polling_place_premises` from stalls.
- [x] What about running the first import while there are pending stalls that are unofficial
- [x] During batch loading of new polling places: Add a 'CHECK' status that logs the old (user-entered) name and address and the new official name and address.

# Admin Console
## Manage Elections
- [x] Create Election, including:
  - [x] Election opening date (the date from which we accept polling places)
- [x] Edit Election
- [x] Set Active Election
- [x] Add/replace polling booths for election: GUI or script -> both to automatically update/replace in Carto. Complexity re updating booths closer to release date when we've mapped stuff already?

## Polling Booths
- [x] Better "Approve and Save" workflow for stalls
- [x] Search for polling places (autocomplete)
- [x] Edit Booth
- [x] Edit Polling Place Type en masse
- [x] On approval, the user that submitted the stall should be emailed a confirmation
- [x] Polling booth info card
- [x] Stall info card
- [x] Record user name, email, booth location (at least LGA - for targeted comms) once booth is approved
- [x] Automatically derive polling place type from stored data (e.g. list of public schools) and historical sausage data
- [x] Predictive chance of sausage based on historical data, maybe on type of polling place?
- ~ESS / Snag Voting integration for Grant's fundraising efforts. Ads?~
- [x] Sticky polling place search box for faster turnover
- [x] Focusing the polling place searcher should highlight everything in there (efficiency)
- [x] Loader: Handle duplicate polling places (Usually caused by the next task...)
- [x] Loader: What to do about polling places spanning multiple or all divisions?
- [x] Write better copy for the "Stall Submitted" and "Stall Approved" emails.
- [x] Download as CSV/XLS

# Public Site
- [x] Make it faster and more lightweight!
- [x] Close accepting booths once election day is over
- [x] Election opening date (the date from which we accept polling places)
- [x] What can we do to make dupey polling places (e.g. Uniting Church) more obvious as to which one the user has selected?
